# run ss3 models in the user-examples model, to make sure they all work
name: call-check-ss3-models-run
on:
  workflow_dispatch:
  pull_request:
    branches: [main]
  push:
    branches: [main]
jobs:
  call-workflow:
    uses: nmfs-stock-synthesis/workflows/.github/workflows/check-ss3-models-run.yml@main
