# run ss3 models in the user-examples model, to make sure they all work
name: call-check-ss3-models-run
on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'model_files/**'
    branches: [main]
  push:
    paths:
      - 'model_files/**'
    branches: [main]
jobs:
  update-user-example-models:
    runs-on: ubuntu-latest
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      R_KEEP_PKG_SOURCE: yes

    steps:

      - name: Checkout repo
        uses: actions/checkout@v3
